### Create new item
POST http://localhost:8080/
Content-Type: application/json

{
  "id": 999,
  "text": "content"
}


### Retrieve item
GET http://localhost:8080/2/


### Delete item
DELETE http://localhost:8080/2/
